export const ENDPOINTS = {
    APPROVE_USER: '/approveUser',
    DECLINE_USER: '/declineUser',
    FILTER_USER: '/filterUser',
    FILTER_COMPANY: '/filterCompany',
    OBTAIN_COMPANY: '/obtainCompany',
    OBTAIN_MANAGER: '/obtainManager',
    CREATE_THEATER: '/createTh',
    OBTAIN_EMPLOYEE: '/obtainEmployee',
    OBTAIN_THEATER: '/obtainTheater',
    ADMIN_CREATE_MOVIE: '/AdminCreateMovie',
    MANAGER_FILTER_THEATER_OVERVIEW: '/ManagerFilterTheater',
    MANAGER_SCHEDULE_MOVIE : '/ManagerScheduleMovie',
    FILTER_MOVIE: '/filterMovie',
    GET_ALL_MOVIE: '/getAllMovie',
    GET_ALL_THEATER_STATE: '/getAllTheaterState',
    GET_USER_CARD_NUMBER : '/getUserCardNum',
    CUSTOMER_VIEW_MOV: '/customerViewMov',
    GET_CUSTOMER_VIEW_HISTORY: '/getCustomerViewHistory',
    GET_ALL_THEATER: '/getAllTheater',
    USER_FILTER_THEATER: '/userFilerTheater',
    USER_VISIT_THEATER: '/userVisitTheater',
    USER_FILTER_VISIT_HISTORY: '/userFilterVisitHistory',
    LOGIN: '/valid_login',
    USER_REG:'/recordUserRegister',
    ADD_CARD:'/addCard',
    REMOVE_CARD:'/removeCard',
    ADD_MAGCARD:'/addManagerCard',
    BACK_TO_FUNC: '/backToFunctionality'
};

